export default  {
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  KID_ADDED: 'KID_ADDED',
  START_FETCHING_KIDS: 'START_FETCHING_KIDS',
  END_FETCHING_KIDS: 'END_FETCHING_KIDS',
  END_FETCHING_KID: 'END_FETCHING_KID',
  API_ERROR: 'API_ERROR',
  KID_UPDATED: 'KID_UPDATED',
  ADDED_UPDATE: 'ADDED_UPDATE',
  MESSAGE_SENT: 'MESSAGE_SENT',
  FETCHED_MESSAGE: 'FETCHED_MESSAGE',
  FETCHED_SPONSORS: 'FETCHED_SPONSORS',
  ADDED_SPONSOR: 'ADDED_SPONSOR'
}