export const USER_LOGGED_IN = 'USER_LOGGED_IN';

export const KID_ADDED = 'KID_ADDED';

export const KIDS_FETCHED = 'KIDS_FETCHED';

export const API_ERROR = 'API_ERROR';

export const KID_UPDATED = 'KID_UPDATED';

export const ADDED_UPDATE = 'ADDED_UPDATE';

export const UPDATE_DELETED = 'UPDATE_DELETED';

export const MESSAGE_SENT = 'MESSAGE_SENT';

export const FETCHED_MESSAGE = 'FETCHED_MESSAGE';

export const FETCHED_SPONSORS = 'FETCHED_SPONSORS';

export const FETCHED_UPDATES = 'FETCHED_UPDATES';

export const ADDED_SPONSOR = 'ADDED_SPONSOR';

export const FILES_UPLOADED = 'FILES_UPLOADED';

export const KID_DELETED = 'KID_DELETED';

export const KID_ARCHIVED = 'KID_ARCHIVED';

export const UPDATE_EDITED = 'UPDATE_EDITED';
